channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python dependencies
  - python=3.9
  - pip=23
  - black
  - mypy
  # corpus_filtering dependencies
  - stanfordcorenlp=3.9
  - stanza=1.5
  - nltk=3.8
  # lm-training submodule dependencies
  - pytorch=2.*
  - transformers>=4.30
  - accelerate>=0.20.3
  - hydra-core=1.3.*
  - strenum
  # BLiMP Evaluation dependencies
  - minicons
  - datasets
