channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - pytorch-cuda=11.6
  - stanfordcorenlp=3.9
  - stanza=1.4
  - nltk=3.8
  - python=3.9
  - black=23.1
  - mypy=1.0
