channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core Python dependencies
  - python=3.9
  - pip=23
  - black
  - mypy
  - tqdm
  - types-tqdm
  # corpus_filtering dependencies
  - stanfordcorenlp=3.9
  - stanza=1.5
  - nltk=3.8
  # lm-training submodule dependencies
  - pytorch=2.*
  - pytorch-cuda=11.*
  - transformers=4.*
  - accelerate
  - hydra-core=1.3.*
  - strenum
