# @package _global_
defaults:
  - override /model/config: lstm
  - _self_
model_arch: lstm
model:
  config: # redundant but included for completeness
    embedding_dim: 1024
    hidden_dim: 1024
    num_layers: 2
    dropout_p: 0.1
    tie_weights: True
